<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<title>yuh library: CatchCxxExceptionsTest Class Reference</title>

<link href="../../tabs.css" rel="stylesheet" type="text/css"/>
<link href="../../doxygen.css" rel="stylesheet" type="text/css" />
<link href="../../navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../jquery.js"></script>
<script type="text/javascript" src="../../resize.js"></script>
<script type="text/javascript" src="../../navtree.js"></script>
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
<link href="../../search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="../../search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { searchBox.OnSelectItem(0); });
</script>

</head>
<body>
<div id="top"><!-- do not remove this div! -->


<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  
  
  <td style="padding-left: 0.5em;">
   <div id="projectname">yuh library
   
   </div>
   
  </td>
  
  
  
 </tr>
 </tbody>
</table>
</div>

<!-- Generated by Doxygen 1.7.6.1 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "../../search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="../../index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="../../namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="../../annotated.html"><span>Classes</span></a></li>
      <li><a href="../../files.html"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="../../search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="../../search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="../../annotated.html"><span>Class&#160;List</span></a></li>
      <li><a href="../../classes.html"><span>Class&#160;Index</span></a></li>
      <li><a href="../../hierarchy.html"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="../../functions.html"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div>
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
  initNavTree('d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html','../../');
</script>
<div id="doc-content">
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a>  </div>
  <div class="headertitle">
<div class="title">CatchCxxExceptionsTest Class Reference</div>  </div>
</div><!--header-->
<div class="contents">
<!-- doxytag: class="gtest_catch_exceptions_test::CatchCxxExceptionsTest" -->
<p><a href="../../db/d27/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest-members.html">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a5a885e791aafe476fdd5c27e892d03aa">testCatchesCxxExceptionsInFixtureConstructor</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a39d0315d69750ddc3d777d5b554e277d">testCatchesCxxExceptionsInFixtureDestructor</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#afd8e6fe37eb76af800212138fd3ffb27">testCatchesCxxExceptionsInSetUpTestCase</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a2c885c7394e8890932e2946135f2c8a7">testCatchesCxxExceptionsInTearDownTestCase</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a244265aa2935ac2803cc16f21ace9d1e">testCatchesCxxExceptionsInSetUp</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a5333d1dbcd9a372f5d61300775bc5305">testCatchesCxxExceptionsInTearDown</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ab0c384270ee0a7d906d7443378644619">testCatchesCxxExceptionsInTestBody</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a35bedaabb28fea1fd611e99a9a6a14fe">testCatchesNonStdCxxExceptions</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a43283026c9019e592f3be2d01f04a492">testUnhandledCxxExceptionsAbortTheProgram</a></td></tr>
</table>
<hr/><a name="details" id="details"></a><h2>Detailed Description</h2>
<div class="textblock"><div class="fragment"><pre class="fragment">Tests C++ exception-catching behavior.

   Tests in this test case verify that:
   * C++ exceptions are caught and logged as C++ (not SEH) exceptions
   * Exception thrown affect the remainder of the test work flow in the
     expected manner.
</pre></div> 
<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00101">101</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
</div><hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="a5a885e791aafe476fdd5c27e892d03aa"></a><!-- doxytag: member="gtest_catch_exceptions_test::CatchCxxExceptionsTest::testCatchesCxxExceptionsInFixtureConstructor" ref="a5a885e791aafe476fdd5c27e892d03aa" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def <a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a5a885e791aafe476fdd5c27e892d03aa">testCatchesCxxExceptionsInFixtureConstructor</a> </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00110">110</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
<div class="fragment"><pre class="fragment"><a name="l00110"></a><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a5a885e791aafe476fdd5c27e892d03aa">00110</a> 
<a name="l00111"></a>00111   <span class="keyword">def </span><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a5a885e791aafe476fdd5c27e892d03aa">testCatchesCxxExceptionsInFixtureConstructor</a>(self):
<a name="l00112"></a>00112     self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span>
<a name="l00113"></a>00113                  <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span>
<a name="l00114"></a>00114                  <span class="stringliteral">&#39;in the test fixture\&#39;s constructor&#39;</span>
<a name="l00115"></a>00115                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00116"></a>00116     self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,
<a name="l00117"></a>00117                  <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span>
<a name="l00118"></a>00118                  <span class="stringliteral">&#39;&quot;CxxExceptionInConstructorTest&quot; (no quotes) &#39;</span>
<a name="l00119"></a>00119                  <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)

</pre></div>
</div>
</div>
<a class="anchor" id="a39d0315d69750ddc3d777d5b554e277d"></a><!-- doxytag: member="gtest_catch_exceptions_test::CatchCxxExceptionsTest::testCatchesCxxExceptionsInFixtureDestructor" ref="a39d0315d69750ddc3d777d5b554e277d" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def <a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a39d0315d69750ddc3d777d5b554e277d">testCatchesCxxExceptionsInFixtureDestructor</a> </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00120">120</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
<div class="fragment"><pre class="fragment"><a name="l00120"></a><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a39d0315d69750ddc3d777d5b554e277d">00120</a> 
<a name="l00121"></a>00121   <span class="keyword">def </span><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a39d0315d69750ddc3d777d5b554e277d">testCatchesCxxExceptionsInFixtureDestructor</a>(self):
<a name="l00122"></a>00122     self.assert_(<span class="stringliteral">&#39;C++ exception with description &#39;</span>
<a name="l00123"></a>00123                  <span class="stringliteral">&#39;&quot;Standard C++ exception&quot; thrown &#39;</span>
<a name="l00124"></a>00124                  <span class="stringliteral">&#39;in the test fixture\&#39;s destructor&#39;</span>
<a name="l00125"></a>00125                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00126"></a>00126     self.assert_(<span class="stringliteral">&#39;CxxExceptionInDestructorTest::TearDownTestCase() &#39;</span>
<a name="l00127"></a>00127                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00128"></a>00128                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)

</pre></div>
</div>
</div>
<a class="anchor" id="a244265aa2935ac2803cc16f21ace9d1e"></a><!-- doxytag: member="gtest_catch_exceptions_test::CatchCxxExceptionsTest::testCatchesCxxExceptionsInSetUp" ref="a244265aa2935ac2803cc16f21ace9d1e" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def <a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a244265aa2935ac2803cc16f21ace9d1e">testCatchesCxxExceptionsInSetUp</a> </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00157">157</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
<div class="fragment"><pre class="fragment"><a name="l00157"></a><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a244265aa2935ac2803cc16f21ace9d1e">00157</a> 
<a name="l00158"></a>00158   <span class="keyword">def </span><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a244265aa2935ac2803cc16f21ace9d1e">testCatchesCxxExceptionsInSetUp</a>(self):
<a name="l00159"></a>00159     self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span>
<a name="l00160"></a>00160                  <span class="stringliteral">&#39; thrown in SetUp()&#39;</span>
<a name="l00161"></a>00161                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00162"></a>00162     self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDownTestCase() &#39;</span>
<a name="l00163"></a>00163                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00164"></a>00164                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00165"></a>00165     self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest destructor &#39;</span>
<a name="l00166"></a>00166                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00167"></a>00167                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00168"></a>00168     self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTest::TearDown() &#39;</span>
<a name="l00169"></a>00169                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00170"></a>00170                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00171"></a>00171     self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> EX_BINARY_OUTPUT,
<a name="l00172"></a>00172                  <span class="stringliteral">&#39;This failure belongs in this test only if &#39;</span>
<a name="l00173"></a>00173                  <span class="stringliteral">&#39;&quot;CxxExceptionInSetUpTest&quot; (no quotes) &#39;</span>
<a name="l00174"></a>00174                  <span class="stringliteral">&#39;appears on the same line as words &quot;called unexpectedly&quot;&#39;</span>)

</pre></div>
</div>
</div>
<a class="anchor" id="afd8e6fe37eb76af800212138fd3ffb27"></a><!-- doxytag: member="gtest_catch_exceptions_test::CatchCxxExceptionsTest::testCatchesCxxExceptionsInSetUpTestCase" ref="afd8e6fe37eb76af800212138fd3ffb27" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def <a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#afd8e6fe37eb76af800212138fd3ffb27">testCatchesCxxExceptionsInSetUpTestCase</a> </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00129">129</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
<div class="fragment"><pre class="fragment"><a name="l00129"></a><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#afd8e6fe37eb76af800212138fd3ffb27">00129</a> 
<a name="l00130"></a>00130   <span class="keyword">def </span><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#afd8e6fe37eb76af800212138fd3ffb27">testCatchesCxxExceptionsInSetUpTestCase</a>(self):
<a name="l00131"></a>00131     self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span>
<a name="l00132"></a>00132                  <span class="stringliteral">&#39; thrown in SetUpTestCase()&#39;</span>
<a name="l00133"></a>00133                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00134"></a>00134     self.assert_(<span class="stringliteral">&#39;CxxExceptionInConstructorTest::TearDownTestCase() &#39;</span>
<a name="l00135"></a>00135                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00136"></a>00136                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00137"></a>00137     self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest constructor &#39;</span>
<a name="l00138"></a>00138                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00139"></a>00139                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00140"></a>00140     self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest destructor &#39;</span>
<a name="l00141"></a>00141                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00142"></a>00142                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00143"></a>00143     self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::SetUp() &#39;</span>
<a name="l00144"></a>00144                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00145"></a>00145                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00146"></a>00146     self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest::TearDown() &#39;</span>
<a name="l00147"></a>00147                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00148"></a>00148                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00149"></a>00149     self.assert_(<span class="stringliteral">&#39;CxxExceptionInSetUpTestCaseTest test body &#39;</span>
<a name="l00150"></a>00150                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00151"></a>00151                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)

</pre></div>
</div>
</div>
<a class="anchor" id="a5333d1dbcd9a372f5d61300775bc5305"></a><!-- doxytag: member="gtest_catch_exceptions_test::CatchCxxExceptionsTest::testCatchesCxxExceptionsInTearDown" ref="a5333d1dbcd9a372f5d61300775bc5305" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def <a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a5333d1dbcd9a372f5d61300775bc5305">testCatchesCxxExceptionsInTearDown</a> </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00175">175</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
<div class="fragment"><pre class="fragment"><a name="l00175"></a><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a5333d1dbcd9a372f5d61300775bc5305">00175</a> 
<a name="l00176"></a>00176   <span class="keyword">def </span><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a5333d1dbcd9a372f5d61300775bc5305">testCatchesCxxExceptionsInTearDown</a>(self):
<a name="l00177"></a>00177     self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span>
<a name="l00178"></a>00178                  <span class="stringliteral">&#39; thrown in TearDown()&#39;</span>
<a name="l00179"></a>00179                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00180"></a>00180     self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest::TearDownTestCase() &#39;</span>
<a name="l00181"></a>00181                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00182"></a>00182                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00183"></a>00183     self.assert_(<span class="stringliteral">&#39;CxxExceptionInTearDownTest destructor &#39;</span>
<a name="l00184"></a>00184                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00185"></a>00185                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)

</pre></div>
</div>
</div>
<a class="anchor" id="a2c885c7394e8890932e2946135f2c8a7"></a><!-- doxytag: member="gtest_catch_exceptions_test::CatchCxxExceptionsTest::testCatchesCxxExceptionsInTearDownTestCase" ref="a2c885c7394e8890932e2946135f2c8a7" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def <a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a2c885c7394e8890932e2946135f2c8a7">testCatchesCxxExceptionsInTearDownTestCase</a> </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00152">152</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
<div class="fragment"><pre class="fragment"><a name="l00152"></a><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a2c885c7394e8890932e2946135f2c8a7">00152</a> 
<a name="l00153"></a>00153   <span class="keyword">def </span><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a2c885c7394e8890932e2946135f2c8a7">testCatchesCxxExceptionsInTearDownTestCase</a>(self):
<a name="l00154"></a>00154     self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span>
<a name="l00155"></a>00155                  <span class="stringliteral">&#39; thrown in TearDownTestCase()&#39;</span>
<a name="l00156"></a>00156                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)

</pre></div>
</div>
</div>
<a class="anchor" id="ab0c384270ee0a7d906d7443378644619"></a><!-- doxytag: member="gtest_catch_exceptions_test::CatchCxxExceptionsTest::testCatchesCxxExceptionsInTestBody" ref="ab0c384270ee0a7d906d7443378644619" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def <a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ab0c384270ee0a7d906d7443378644619">testCatchesCxxExceptionsInTestBody</a> </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00186">186</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
<div class="fragment"><pre class="fragment"><a name="l00186"></a><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ab0c384270ee0a7d906d7443378644619">00186</a> 
<a name="l00187"></a>00187   <span class="keyword">def </span><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#ab0c384270ee0a7d906d7443378644619">testCatchesCxxExceptionsInTestBody</a>(self):
<a name="l00188"></a>00188     self.assert_(<span class="stringliteral">&#39;C++ exception with description &quot;Standard C++ exception&quot;&#39;</span>
<a name="l00189"></a>00189                  <span class="stringliteral">&#39; thrown in the test body&#39;</span>
<a name="l00190"></a>00190                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00191"></a>00191     self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDownTestCase() &#39;</span>
<a name="l00192"></a>00192                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00193"></a>00193                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00194"></a>00194     self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest destructor &#39;</span>
<a name="l00195"></a>00195                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00196"></a>00196                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)
<a name="l00197"></a>00197     self.assert_(<span class="stringliteral">&#39;CxxExceptionInTestBodyTest::TearDown() &#39;</span>
<a name="l00198"></a>00198                  <span class="stringliteral">&#39;called as expected.&#39;</span>
<a name="l00199"></a>00199                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)

</pre></div>
</div>
</div>
<a class="anchor" id="a35bedaabb28fea1fd611e99a9a6a14fe"></a><!-- doxytag: member="gtest_catch_exceptions_test::CatchCxxExceptionsTest::testCatchesNonStdCxxExceptions" ref="a35bedaabb28fea1fd611e99a9a6a14fe" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def <a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a35bedaabb28fea1fd611e99a9a6a14fe">testCatchesNonStdCxxExceptions</a> </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00200">200</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
<div class="fragment"><pre class="fragment"><a name="l00200"></a><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a35bedaabb28fea1fd611e99a9a6a14fe">00200</a> 
<a name="l00201"></a>00201   <span class="keyword">def </span><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a35bedaabb28fea1fd611e99a9a6a14fe">testCatchesNonStdCxxExceptions</a>(self):
<a name="l00202"></a>00202     self.assert_(<span class="stringliteral">&#39;Unknown C++ exception thrown in the test body&#39;</span>
<a name="l00203"></a>00203                  <span class="keywordflow">in</span> EX_BINARY_OUTPUT)

</pre></div>
</div>
</div>
<a class="anchor" id="a43283026c9019e592f3be2d01f04a492"></a><!-- doxytag: member="gtest_catch_exceptions_test::CatchCxxExceptionsTest::testUnhandledCxxExceptionsAbortTheProgram" ref="a43283026c9019e592f3be2d01f04a492" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def <a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a43283026c9019e592f3be2d01f04a492">testUnhandledCxxExceptionsAbortTheProgram</a> </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>self</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Definition at line <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html#l00204">204</a> of file <a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a>.</p>
<div class="fragment"><pre class="fragment"><a name="l00204"></a><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a43283026c9019e592f3be2d01f04a492">00204</a> 
<a name="l00205"></a>00205   <span class="keyword">def </span><a class="code" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html#a43283026c9019e592f3be2d01f04a492">testUnhandledCxxExceptionsAbortTheProgram</a>(self):
<a name="l00206"></a>00206     <span class="comment"># Filters out SEH exception tests on Windows. Unhandled SEH exceptions</span>
<a name="l00207"></a>00207     <span class="comment"># cause tests to show pop-up windows there.</span>
<a name="l00208"></a>00208     FITLER_OUT_SEH_TESTS_FLAG = FILTER_FLAG + <span class="stringliteral">&#39;=-*Seh*&#39;</span>
<a name="l00209"></a>00209     <span class="comment"># By default, Google Test doesn&#39;t catch the exceptions.</span>
<a name="l00210"></a>00210     uncaught_exceptions_ex_binary_output = gtest_test_utils.Subprocess(
<a name="l00211"></a>00211         [EX_EXE_PATH,
<a name="l00212"></a>00212          NO_CATCH_EXCEPTIONS_FLAG,
<a name="l00213"></a>00213          FITLER_OUT_SEH_TESTS_FLAG]).output
<a name="l00214"></a>00214 
<a name="l00215"></a>00215     self.assert_(<span class="stringliteral">&#39;Unhandled C++ exception terminating the program&#39;</span>
<a name="l00216"></a>00216                  <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)
<a name="l00217"></a>00217     self.assert_(<span class="stringliteral">&#39;unexpected&#39;</span> <span class="keywordflow">not</span> <span class="keywordflow">in</span> uncaught_exceptions_ex_binary_output)
<a name="l00218"></a>00218 

</pre></div>
</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>gtest-1.6.0/test/<a class="el" href="../../df/d22/gtest__catch__exceptions__test_8py_source.html">gtest_catch_exceptions_test.py</a></li>
</ul>
</div><!-- contents -->
</div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(0)"><span class="SelectionMark">&#160;</span>All</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(1)"><span class="SelectionMark">&#160;</span>Classes</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(2)"><span class="SelectionMark">&#160;</span>Namespaces</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(3)"><span class="SelectionMark">&#160;</span>Files</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(4)"><span class="SelectionMark">&#160;</span>Functions</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(5)"><span class="SelectionMark">&#160;</span>Variables</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(6)"><span class="SelectionMark">&#160;</span>Typedefs</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(7)"><span class="SelectionMark">&#160;</span>Enumerations</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(8)"><span class="SelectionMark">&#160;</span>Enumerator</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(9)"><span class="SelectionMark">&#160;</span>Friends</a><a class="SelectItem" href="javascript:void(0)" onclick="searchBox.OnSelectItem(10)"><span class="SelectionMark">&#160;</span>Defines</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

  <div id="nav-path" class="navpath">
    <ul>
      <li class="navelem"><a class="el" href="../../dd/dbf/namespacegtest__catch__exceptions__test.html">gtest_catch_exceptions_test</a>      </li>
      <li class="navelem"><a class="el" href="../../d4/d31/classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest.html">CatchCxxExceptionsTest</a>      </li>

    <li class="footer">Generated on Sun Aug 19 2012 21:31:01 for yuh library by
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.7.6.1 </li>
   </ul>
 </div>


</body>
</html>
